# Generated by Django 4.1.3 on 2022-11-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
