# Generated by Django 4.1.3 on 2022-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('item_cost', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('volume', models.PositiveIntegerField()),
            ],
        ),
    ]
