# Generated by Django 4.1.2 on 2022-11-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('cost', models.FloatField()),
                ('stock_qty', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
