# Generated by Django 4.1.3 on 2022-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='valume',
            field=models.IntegerField(),
        ),
    ]
